# Disable some built-in rules
config:
  descriptive-link-text: false
  heading-increment: false
  line-length: false
  no-alt-text: false
  no-bare-urls: false
  no-emphasis-as-heading: false
  no-inline-html: false
